name: Build and Deploy to Vercel

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: 📥 Récupération du code
        uses: actions/checkout@v4

      - name: ⚙️ Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Installation des dépendances
        run: npm install

      - name: 🚀 Lancement du Build et du Pré-rendu SEO
        run: npm run build

      - name: 🔗 Récupération de la configuration Vercel
        run: |
          rm -rf .vercel
          npx vercel pull --yes --environment=production --token ${{ secrets.VERCEL_TOKEN }}

      - name: 🏗️ Préparation du build Vercel
        run: npx vercel build --prod --token ${{ secrets.VERCEL_TOKEN }}

      - name: 🌐 Déploiement direct sur Vercel
        run: npx vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }}